### PR TITLE
docs(server_tokio_import): added server function

### PR DESCRIPTION
**Pull request by Andrew15-5**
I'm not sure about `pub async`. Shouldn't it be `pub(super) async`?

### CODE REVIEW

**Comment by Andrew15-5** [comment]
So Dioxus doesn't follow 80-char comments? Is it 120 here or something else?

**Review by ealmloff — APPROVED** [review]

**Comment by Andrew15-5** [comment]
Module inside other module? And anchor is indented + inside of the outer module? Will this look good? If you were to use the actual file, then the server functions are private inside the `tokio_module`.

**Comment by ealmloff** [comment]
> Module inside other module? And anchor is indented + inside of the outer module? Will this look good? If you were to use the actual file, then the server functions are private inside the `tokio_module`.

The extra module is just there to make the doc tests compile. It will not show up in the docsite. Try running `cargo check --features doc_test`

**Comment by Andrew15-5** [comment]
I'm not sure if such short functions need the extra verbosity with the variable. Without the variable it's 1 line shorter and the max length is also shorter (even less than 80).

```rs
    #[server]
    async fn get_file_contents() -> Result<String, ServerFnError> {
        // let file = tokio_utilities::read_file(PathBuf::from("path/to/file")).await?;
        // Ok(file)
        Ok(tokio_utilities::read_file(PathBuf::from("path/to/file")).await?)
    }
```

**Pull request merged**
